import type { Metadata } from 'next'
import './globals.css'

import { LoadingProvider, OverlayLoading } from '@/components/loading'
import { Toaster } from '@/components/ui/sonner'
import { Roboto } from 'next/font/google'

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${roboto.className} antialiased`}>
        <LoadingProvider>
          {children}
          <OverlayLoading />
        </LoadingProvider>

        <Toaster position='top-center' richColors duration={2000} />
      </body>
    </html>
  )
}
